export const guestEndpoints = {
  login: "login",
  register: "register",
  confirmRegistration: "confirm-registration",
  forgotPassword: "forgot-password",
  resetPassword: "reset-password",
  resendRegistration: "verify/resend",
  refresh: "refresh",
  me: "me",
  profilePicture: "me/picture",
  anonymizeCheck: "me/anonymize/check",
  anonymize: "me/anonymize",
  dataExport: "me/export",
  menuTree: "menu-tree",
  orders: "orders",
  activeOrders: "orders/active",
  employees: "employees",
  drink: (drinkId) => `drinks/${drinkId}`,
  receipt: (receiptId) => `receipts/${receiptId}`,
};
